#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import os
from bilge_katalog.main import *

if "qt" in sys.argv:
    from PyQt4 import QtGui
    from PyQt4 import QtCore
    import bilge_katalog.mainqt as mainqt
    
    app = QtGui.QApplication(sys.argv)
    language = QtCore.QLocale.system().name()
    locale = "/usr/share/locale/%s/LC_MESSAGES"% language
    if not os.path.isdir(locale):
        locale = "/usr/share/locale/%s/LC_MESSAGES"% language[:2]
    translator = QtCore.QTranslator()
    translator.load("bilge-katalog.qm", locale)
    app.installTranslator(translator)
    window = mainqt.MainWindow()
    window.show()
    sys.exit(app.exec_())

else:
    mainloop()
